[book]
authors = ["Felix Ableitner"]
src = "src"

[language.en]
name = "English"
title = "Lemmy Documentation"

[language.es]
name = "Español"
title = "Documentación Lemmy"

[language.ru]
name = "Русский"
title = "Документация Lemmy"
